name: weight_management
description: A new Flutter application.


publish_to:
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3

  provider: ^4.3.1
  cloud_firestore: ^0.14.1+3
  firebase_core: ^0.5.0+1
  intl: ^0.16.1
  http: ^0.12.1
  flutter_dotenv: ^2.1.0
  table_calendar: ^2.2.3
  image_picker: ^0.6.7+12
  firebase_storage: ^4.0.1
  introduction_screen: ^1.0.9
  shared_preferences: ^0.5.12+4
  charts_flutter: ^0.9.0
  firebase_auth: ^0.18.3+1
  flushbar: ^1.10.4



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^0.1.9
  flutter_launcher_icons: "^0.8.0"
flutter_native_splash:
  image: "assets/images/splash.png"
  color: "ffffff"
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/splash.png"

flutter:
  assets:
    - assets/images/splash.png

  uses-material-design: true
